env:
 global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: "Cmkp5xsTkM1kpfkK3EnKjQ6fglCrE056tCjvGu2LTyUma7xZqXd27yc4wEXs8V2qRaLmWqqxyEDMZ5B1OO8TFxm1YsqIzoKm7SfSh7Z6QQaznLAubMpy96iQr5fzQSUC8XshEdKuxNyXwBg8F2UIh/SA/jP7x0hrMNzWO84yujw="
  - secure: "IY94qbqJvqrwj76J/YVKcH5OtIpXmbg97OsMIowPAyRBE6VdEXkmVWQ1HoonpVhdEZXZ8v9pTSV6y92g3T78Jf21iqWCG2Zz+n2woPzcpCi4zCZXpv1fJgo2eIUqNkjxSZDFRtTesGsvRjIcFDvIxjLZHYuB1az1CpsWGHt3LLs="
  - secure: "OrDel/pu3KcHddFf3n05Q0O+68o21yTCfCPPHTXOyUrj/Ilbq6tbcI2wuNOMibsXvV1eZJH/MjB6xZ2KvI8xXWBmO0Fhd3VMxtrHadfFxmDDAfSIFzx42DBPm6ELCJtGAKIbIUnhieqMzFXvwh6Aegvj0i+u8tKaBRqCWXq6G8A="
  - secure: "T5Gbchxmr+DcrP1MHzOdUQN68LjY40wp/muYzdKSoSdTwgsoipU4uEVJeTlvoliobSfNQiBZpWQfsUcHhNrp5CVN8kzlcO0Et8A1Gk6ET3trpGo5LFY7IjOEQ+O6tdRwEqkM5x8LKnUafEMDpmzaznA+uEf2jMRWx4EhMyMcf6s="
  - secure: "LqU2xFLn3wsmU2LXicdfn3MCB3v0Yf+pUQAnCAF1pAWLE+sBDCIa6taZwPxUN00W79pd4S7XvT2kq4CpzsdQPPZQ4wurzCvumdvmafr6Odde5pTFFdbrqHbBIn48P+vYNJUFnKL55b1d/E38XyfUMxeSm9B+VTKvBs3YtftKG7Y="
  - secure: "UrjfyXOx50rBKWt/afxCp/if+E4In53PGBilNslwTbU8HbgiGGCv1uvlaXAic02b+vunDerXZD+XYOxNvUdmD+RKVAKAi6BUk+XEnPKOuRg4EfCbrRgqpaTEWVYu9OdpE4jXAwxNNQuq78qvfwI7lq/Xg2CA5Olz2dNYPOOpXzI="
  - secure: "e6gc0dEE4Ehm3lYKzMv9AHNN6x6ou7jRv0gweMHXf17zJ4Iu7QOw+3bTCImsjrAt8046XD0Dv19FVT4ZBOZuU66HL+k0IMF9jh989WU3dQ41Dv5FrWKn1kt/heQ87H04L4bnhbI20ftOmy1GFCWZkB0TycgyXoQEt/X+6KLNd0k="

language: python
python:
  - "2.7"

install: "pip install -r test/requirements.txt"

before_script:
   - gem install travis-artifacts --no-ri --no-rdoc
   - git submodule update --init --recursive

script: ./build.sh
