env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: WLDfyxIpIe+o4U2kmAYH3fzLzG391hdQqnQeGqMPWMNZPbJw+Hw7N8i1yTuLNy44CdaN0Sn6jZssbxsWNMpz9EjsXD5/CySprRV992FLYXBVyNZcMOCMgDZ32IwAU+KA3VanILhI04il5QUROELBoFU9D730C2j87i+5OiAuLPg=
  - secure: L7W+dkWzCnW+5zPiK9IhILQoIuwdJkL7ioP6n+Lcv7rAr2SsYpXAda9IvaNimzgogRL49fLVDRNM142egmjyH2NlmcRH2xPJo1jz7My6g1GrGTkotcbfMrXYiSbrp/GjUZQmt0DYIyYG2qdMPQ/rKPSpQTFLHjL343LGmwoQTvs=
  - secure: Oh1Y0F/i6BkzCbx+odLYxTSdAVGnqzE6a5NnOBhQe9XxYOTR8VkGP/QClI5E2u1TErvP2gaSTUUA/AUjQWYx2QjPrO0cgv3wxH9uv0Cwy2Yw9NuUafSxvfZRdE+k6EFXD1fgNMZfHvqNt7lVC9BVKb2GDn3vWaoF4kXomXDHZvs=
  - secure: HqQwdfMnLd84IfrfFhxz2wcXCuHBNXldKMtwdPJmDRTX4V9FMz4eVoC12F6moZXKDScytL4uHKbavJyt4kf742zaWo4SiogsMtXhOQDk5tA17+jk+yELBbnVIs/7KdcNkO9vKtqGDINarFMbexDIMBElWlXk8Xq+YIPsnacey5Q=
  - secure: av9mANAtzw2upv5uamQMhN+YHeyFid3rMqzpp+C2YoJ6p5bQD7gRKDIeLC/cSCZDPZDrG1jaSp4I33h2equx5n1ke8DBmy5p231s89lYV+cwZp4R+OEgngupRMc+io7PgmAWm1/CE/sleGVEBpL2gwgJO59AMxgDDjCsjMaKBm8=
  - secure: OzABb8Emc4T5eb2uOoJQ9i113EnR9FSpfaSq0g5BdQHxzvLnSNoM8IlXqsrWJ52ql0p4oVt3JtN72U+ML+5UE6SXgJ0H7WXK25r7sLDgWAG9KZvEfPW/Qe5YZ/rshOKZmZtmhNC85+93uUz97J2bJJ0l1ikVzAy8EGIBRrz9j+k=
  - secure: XhMYUn76siPiHapy+36uOdwfz2sz/cPOCNloWCTmfYZn9rAJ3i0vqUqB5h+Qu2t5gd7rUX7+/hAcRmC+t54ZpdlWnzsX6lcvjOujFDdOndifILSFRyfBXrTCtwZZ6R5mhHDrJVsnj9F2JsONoG7GYdmFjT7ZiH6jdBc9o/W6UeQ=
language: python
python:
- '2.7'
install: pip install -r test/requirements.txt
before_script:
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
