env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: WLDfyxIpIe+o4U2kmAYH3fzLzG391hdQqnQeGqMPWMNZPbJw+Hw7N8i1yTuLNy44CdaN0Sn6jZssbxsWNMpz9EjsXD5/CySprRV992FLYXBVyNZcMOCMgDZ32IwAU+KA3VanILhI04il5QUROELBoFU9D730C2j87i+5OiAuLPg=
  - secure: L7W+dkWzCnW+5zPiK9IhILQoIuwdJkL7ioP6n+Lcv7rAr2SsYpXAda9IvaNimzgogRL49fLVDRNM142egmjyH2NlmcRH2xPJo1jz7My6g1GrGTkotcbfMrXYiSbrp/GjUZQmt0DYIyYG2qdMPQ/rKPSpQTFLHjL343LGmwoQTvs=
  - secure: Oh1Y0F/i6BkzCbx+odLYxTSdAVGnqzE6a5NnOBhQe9XxYOTR8VkGP/QClI5E2u1TErvP2gaSTUUA/AUjQWYx2QjPrO0cgv3wxH9uv0Cwy2Yw9NuUafSxvfZRdE+k6EFXD1fgNMZfHvqNt7lVC9BVKb2GDn3vWaoF4kXomXDHZvs=
  - secure: fRDj7TbnwNcQEJh8jrkxWzemtEfN+8Ph0iKkJJEmnh9tOFzsqN0A+djXemvZp3h1zCpWNC9WVWCOXpOwnGg40kWd2slgLB6p+Nd6QXEm0GoJZ9EFxI1GhBwm5nR/doDmykLsz2E8swwx3y70FU3Gfn1IyOwn1+OJwyXgGn1E+Us=
  - secure: TiBYz3Pkzv0Ec7sNwTbeJIyMhuqpofpwJN2wysChidU3j8VY8ZowhXCvUN0eAfKW6f0nV/AkXlZetO/C6d+I4HBLary09uoyXdHYO32hSWqmqK7nVel0t7iMv851zkqWz0uwH7PYEc+djKTOBO0/6LSHRfucbSorKxQ353TCMv0=
  - secure: a7Egu1wJV02bnX1T+pCh3C1VYpVc83F0uippcRyr6xInRbpgN126ikBTmZ1nkz3ZsYq6hzVm7sWBpqoqXxnqx/fhsMijllSb72dpG5Blo2ixgKPaah7v17MRCeOAf8076kJb5tOWsSgAbqLApHJNCnJpfF29lexhYMJLe3Tblyk=
  - secure: AK13aKEkHrUd25bTwXhJPKQs1MAsVgURqbeGd1V5nCDBOWNoj2SCkYvFtxM9FKo4Ggpug7q9xhEl4cYtnfI87V4rYMSE/umU40r1bsxqu44E7EAIZfcDNOneb7lk5fpdxqt7niHPFBvDP1JPLuUhDopt2ucj2V7bQINQLMZVigQ=
language: python
python:
- '2.7'
install: pip install -r test/requirements.txt
before_script:
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
